channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - faiss-cpu==1.7
  - ipykernel
  - ipywidgets
  - h5py=3.6
  - tqdm
  - matplotlib==3.5
  - jupyterlab==3.0
  - notebook
  - voila==0.3.0
  - pip:
    - gdown~=4.2
    - -r ./requirements.cpu.txt
    - -r ./requirements.clip.txt

